flask_game/main/routes.py
from flask import render_template, request, Blueprint
from flask_game.models import fp_post

main = Blueprint('main', __name__)

@main.route("/")
@main.route("/home")
def home():
    page = request.args.get('page', 1, type=int)
    posts = fp_post.query.order_by(fp_post.datecreated.desc()).paginate(page=page, per_page=2)
    return render_template('home.html', posts=posts)

@main.route("/about")
def about():
    return render_template('about.html', title='About')

flask_game/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from flask_game import db, bcrypt
from flask_game.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                   RequestResetForm, ResetPasswordForm)
from flask_game.users.utils import send_reset_email, save_picture
from flask_game.models import users_tbl

users = Blueprint('users', __name__)

@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = users_tbl(username=form.username.data, email=form.email.data, passw=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)

@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = users_tbl.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.passw, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)

@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.home'))

@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = users_tbl.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)

@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    user = users_tbl.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.passw = hashed_password
        db.session.commit()
        flash('Your password has been updated', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

#Template lifted, to be changed...
@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)

flask_game/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

flask_game/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
      <div class="media">
        <img class="rounded-circle account-img" src="{{ image_file }}">
        <div class="media-body">
          <h2 class="account-heading">{{ current_user.username }}</h2>
          <p class="text-secondary">{{ current_user.email }}</p>
        </div>
      </div>
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_game/templates/create_game.html
{% extends "layout.html" %}
{% block content %}
    <h1>Create New Game</h1>
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <div class="form-group">
                    {{ form.game_name.label(class="form-control-label") }}

                    {% if form.game_name.errors %}
                        {{ form.game_name(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.game_name.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.game_name(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.input_x_y.label(class="form-control-label") }}
                    {% if form.input_x_y.errors %}
                        {{ form.input_x_y(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.input_x_y.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.input_x_y(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.smooth_x_y1.label(class="form-control-label") }}
                    {% if form.smooth_x_y1.errors %}
                        {{ form.smooth_x_y1(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.smooth_x_y1.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.smooth_x_y1(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.smooth_x_y2.label(class="form-control-label") }}
                    {% if form.smooth_x_y2.errors %}
                        {{ form.smooth_x_y2(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.smooth_x_y2.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.smooth_x_y2(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.filter_method.label(class="form-control-label") }}
                    {% if form.filter_method.errors %}
                        {{ form.filter_method(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.filter_method.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.filter_method(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
{% endblock content %}

flask_game/templates/display_map_preview.html
{% extends "layout.html" %}
{% block content %}
<div class="content-section"></div>
    <title>{{ title }}</title>

    {{ div | safe }}
    {{ form1.hidden_tag() }}
    {{ form2.hidden_tag() }}
    <form method="POST" action="">
        <div class="container">
            <div class="row">
                <div class="col-sm">
                    <div class="form-group">
                        {{ form1.submit_confirm(class="btn btn-outline-info") }}
                    </div>
                </div>
                <div class="col-sm">
                    <div class="form-group">
                        {{ form2.submit_cancel(class="btn btn-outline-warning") }}
                    </div>
                </div>
            </div>
        </div>
    </form>
</div>
<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{% endblock content %}

flask_game/templates/home.html
{% extends "layout.html" %}
{% block content %}
<div class="container text-left mb-4 mt-2">
    <h1 class="text-center">Welcome to Terrarum</h1>
    <p>A realm/city management game with an emphasis on simulation, politics, resource management and war.</p>
</div>

<div class="container mt-2">
{% for post in posts.items %}
    <article class="media content-section">
        <img class="rounded-circle article-img" src="{{ url_for('static', filename='profile_pics/' + post.createdby.image_file) }}">
        <div class="media-body">
            <div class="article-metadata">
                <a class="mr-2">{{ post.createdby.username }}</a>
                <small class="text-muted">{{ post.datecreated.strftime('%Y-%m-%d') }}</small>
            </div>
            <h2><a class="article-title" >{{ post.title }}</a></h2>
            <p class="article-content">{{ post.post }}</p>
        </div>
    </article>
{% endfor %}
{% for page_num in posts.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
    {% if page_num %}
        {% if posts.page == page_num %}
            <a class="btn btn-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% else %}
            <a class="btn btn-outline-info mb-4" href="{{ url_for('main.home', page=page_num) }}">{{ page_num }}</a>
        {% endif %}
    {% else %}
    ...
    {% endif %}
{% endfor %}

</div>
{% endblock content %}

flask_game/templates/join_game.html
{% extends "layout.html" %}
{% block content %}


<div class="content-section text-center">
    <div class="table text-center">
        <title>{{ title }}</title>
        <div class="container text-center">
            {% for table in tables %}
                <thead>
                {{titles[loop.index]}}
                </thead>
                {{ table|safe }}
            {% endfor %}
        </div>
    </div>
    <div class="container"> 
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Pick Game To Join</legend>
                <div class="form-group">
                    {{ form.game.label(class="form-control-label") }}
    
                    {% if form.game.errors %}
                        {{ form.game(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.game.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.game(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>


{% endblock content %}

flask_game/templates/layout.html
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <!-- <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='bootstrap.min.css') }}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.19/css/jquery.dataTables.css">
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
    <script src="https://cdn.plot.ly/plotly-latest.min.js"></script>
    <script type="text/javascript" charset="utf8" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.js"></script>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="{{ url_for('main.home') }}">Terrarum</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('main.home') }}">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{ url_for('main.about') }}">About <span class="sr-only">(current)</span></a>
            </li>
            {% if current_user.is_authenticated and current_user.gameid is number %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Realm Management
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('game_routes.overview') }}">Realm Overview</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('game_routes.overview_peons') }}">Peon Overview</a>
              </div>
            </li>
            {% endif %}
            {% if current_user.is_authenticated %}
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                {{ current_user.username }}
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('game_routes.overview') }}">My Realm</a>
                <a class="dropdown-item" href="#">Action Log</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('create_game.create_new_game') }}">Create New Game</a>
                <a class="dropdown-item" href="{{ url_for('game_map.join_game') }}">Join Game</a>
                <a class="dropdown-item" href="{{ url_for('game_map.set_current_game') }}">Set Current Game</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.account') }}">Account</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.logout') }}">Logout</a>
              </div>
            </li>

            {% else %}

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Login Required
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="{{ url_for('users.login') }}">Login</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="{{ url_for('users.register') }}">Register</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#">Another action</a>
                <a class="dropdown-item" href="#">Something else here</a>
              </div>
            </li>
            {% endif %}

          </ul>
        </div>
      </nav>
      <main role="main" class="container">
        <div class="row">
          <div class="col-md-8">
            {% with messages = get_flashed_messages(with_categories=true) %}
              {% if messages %}
                {% for category, message in messages %}
                  <div class="alert alert-{{ category }}">
                    {{ message }}
                  </div>
                {% endfor %}
              {% endif %}
            {% endwith %}
          </div>
        </div>
    </main>
    <div class="container-fluid">
      {% block content %}{% endblock %}
    </div>
  </body>
</html>

flask_game/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Log In</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.password.label(class="form-control-label") }}
                    {% if form.password.errors %}
                        {{ form.password(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.password.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.password(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-check">
                    {{ form.remember(class="form-check-input") }}
                    {{ form.remember.label(class="form-check-label") }}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
                <small class="text-muted ml-2">
                    <a href="{{ url_for('users.reset_request') }}">Forgot Password?</a>
                </small>
            </div>
        </form>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

flask_game/templates/overview.html
{% extends "layout.html" %}
{% block content %}

<script>
    $(document).ready( function () {
        $('#peontable').DataTable();
    } );
</script>

<div class="table table-bordered table-hover text-light bg-dark">
{% for table in tables %}
            {{ table|safe }}
{% endfor %}
</div>

{% endblock content %}

flask_game/templates/overview_peons.html
{% extends "layout.html" %}
{% block content %}

<script>
    $(document).ready( function () {
        $('#peontable').DataTable();
    } );
</script>

<div class="container-fluid text-center p-4 mb-4">
        <div class="row mb-2">
            <div class="col">
                Peon Overview


            </div>
        </div>
    <div class="row">
        <div class="col">
            <embed type="image/svg+xml" src={{line_data|safe}} style='max-width:1250px'/>
        </div>
        <div class="col">
            <embed type="image/svg+xml" src={{gauge_data|safe}} style='max-width:1250px'/>
        </div>
        <div class="col">
            3
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="table table-hover text-light bg-warning mt-4 p-2">
                {% for table in tables %}
                    {{ table|safe }}
                {% endfor %}
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top" src="static/images/families.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Families</h5>
                    <p class="card-text">Number of peon families: {{ tot_fams }}</p>
                    <p class="card-text">Wealthiest familiy: PLACEHOLDER</p>
                    <p class="card-text">Biggest familiy: PLACEHOLDER</p>
                    <a href="#" class="btn btn-primary">Build More Housing</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 20rem;">  
                <img class="card-img-top" src="static/images/gender.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Genders</h5>
                    <p class="card-text">Male: {{ df_peon_gender.Count[df_peon_gender.Gender == 'Male'].item() }}</p>
                    <p class="card-text">Female: {{ df_peon_gender.Count[df_peon_gender.Gender == 'Female'].item() }}</p>
                    <a href="#" class="btn btn-primary">Build More Housing</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 20rem;"> df_peon_so
                <img class="card-img-top" src="static/images/sex_orientation.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Sexual Orientation</h5>
                    <p class="card-text">Heterosexual: {{ df_peon_so.Count[df_peon_so.Orientation == 'Heterosexual'].item() }}</p>
                    <p class="card-text">Homosexual: {{ df_peon_so.Count[df_peon_so.Orientation == 'Homosexual'].item() }}</p>
                    <p class="card-text">Bisexual: {{ df_peon_so.Count[df_peon_so.Orientation == 'Bisexual'].item() }}</p>
                    <a href="#" class="btn btn-primary">Build More Housing</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top" src="static/images/families.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Peon Families</h5>
                    <p class="card-text">Number of peon families: {{ tot_fams }}</p>
                    <p class="card-text">Wealthiest familiy: PLACEHOLDER</p>
                    <p class="card-text">Biggest familiy: PLACEHOLDER</p>
                    <a href="#" class="btn btn-primary">Build More Housing</a>
                </div>
            </div>
        </div>
        <div class="col">
            <div class="card" style="width: 20rem;">
                <img class="card-img-top" src="static/images/families.jpg" alt="Card image cap">
                <div class="card-body">
                    <h5 class="card-title">Peon Families</h5>
                    <p class="card-text">Number of peon families: {{ tot_fams }}</p>
                    <p class="card-text">Wealthiest familiy: PLACEHOLDER</p>
                    <p class="card-text">Biggest familiy: PLACEHOLDER</p>
                    <a href="#" class="btn btn-primary">Build More Housing</a>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

flask_game/templates/pick_start_location.html
{% extends "layout.html" %}
{% block content %}

<div class="content-section">
    <title>{{ title }}</title>

    {{ div | safe }}
    <div class="container"> 
        <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            {{ form.csrf_token }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Pick Start Location</legend>
                <div class="form-group">
                    {{ form.race.label(class="form-control-label") }}
    
                    {% if form.race.errors %}
                        {{ form.race(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.race.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.race(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.x_position.label(class="form-control-label") }}
    
                    {% if form.x_position.errors %}
                        {{ form.x_position(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.x_position.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.x_position(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.y_position.label(class="form-control-label") }}
    
                    {% if form.y_position.errors %}
                        {{ form.y_position(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.y_position.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.y_position(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
    </div>
</div>


<script src="https://cdnjs.cloudflare.com/ajax/libs/d3/3.5.6/d3.min.js"></script>
<script src="https://cdn.plot.ly/plotly-latest.min.js"></script>

{% endblock content %}

flask_game/templates/set_current_game.html
{% extends "layout.html" %}
{% block content %}



{% endblock content %}